apiVersion: batch/v1
kind: Job
metadata:
  name: data-crunch-job
spec:
  completions: 1
  parallelism: 1
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: crunch
        image: data-crunch:0.1
        command: ["python", "app.py", "/data/large.csv", "value"]
